### ISSUE TITLE
Add the ability to send a message (toast/achievement style) when the day changes

### ISSUE THREAD

**Issue by spencer-wild** [jmanpenilla/AnnouncerPlus#24]
The title pretty much explains the suggestion! I think this would be a pretty cool idea. Preferably at the start of the day, or some other time of the day that the user could set, although I don't know how practical the latter is.

**Comment by Craftizz** [comment]
I think making a command to send a message to a specific player would be more practical and useable for everyone? Then you can use 3rd party plugins to send a message to a specific player at this event or time.

**Comment by spencer-wild** [comment]
i don’t think i understand what you’re suggesting and i feel like it might be something entirely different

**Comment by jmanpenilla** [comment]
I think what Craftizz suggested is correct actually. Broadcasts on the day change seems out of scope for the plugin to me. One of the fields which is meant to be filled out on a feature request (I may have added the issue template after you created the issue) is the "Alternatives you have tried or considered" field. I think with the commands I have added since this issue has been created (specifically in this case, ``/ap broadcasttoast`` and ``/ap sendtoast``) you could very easily have another plugin which runs commands on the day change, and have it run those commands for you.
