### ISSUE TITLE
[Feature Request] Customizability Settings for sounds being played

### ISSUE THREAD

**Issue by nuttyNaoko** [jmanpenilla/AnnouncerPlus#39]
**Is your feature request related to a problem? Please describe.**
This is not really a problem, more of a customization limit.

**Describe the solution you'd like**
Have the config file changed in a way that you can choose what output the sound gets played in (master, ambient, hostile, ...)
Get a volume option that could be set in numbers from 0 to 100
Get a pitch option to adjust the sound pitch amount

```
{
join-sounds="minecraft:entity.strider.happy"
    sound-volume="82"
    sound-pitch="46"
}
```

This could be cool to add but might need more effort, animated sounds, or different sounds played one after the other.
This would be configured somewhat similarly to how text is animated with tags.

```
<piano><fast><hostile.46> pitch.0:pitch.1:pitch.2:pitch.0:pitch.1:pitch.2
<xylo><slow><master.82> pitch.0:pitch.1:pitch.2:pitch.0:pitch.1:pitch.2

I'm using the noteblock sounds here because it would be impossible to have a tag for every single sound in the game.

```

**Describe alternatives you've considered**
I tried inputting the same command you'd use in a command block
`/playsound block.note_block.xylophone master @p ~ ~ ~ 100 2` Obviously this did not work.

**Additional nitpicks**
Config is sometimes hard to read, perhaps adding some structure with big titles could help players configure it easily without
having to read every line carefully to make sure they're in the right section. Perhaps something like this to give you an idea:

```
#~~~~~~~~~~~~~~~~~~~ #
#   JOIN SETTINGS    #
#~~~~~~~~~~~~~~~~~~~~#

join-section {
    # Settings relating to showing an Action Bar to the joining Player
    action-bar-settings {
        # Seconds of duration for the Action Bar to stay on screen
        duration-seconds=8
        # Should the fade out animation of the Action Bar be enabled?
        enable-fade-out=false
        # The text for the Action Bar. Set to "" (empty string) to disable. Accepts animations
        text=""

```

**Comment by jmanpenilla** [comment]
The config is easy enough to configure, especially for the level of customization offered. I recommend setting your editor to parse it as JSON to get syntax highlighting. (They are HOCON files, however the syntax is very similar to JSON)
Adding a bunch of empty lines and headers is the opposite of useful in my opinion and would make the configs even more bloated in size/length than they already are.

In the far future I do have a plan to restructure the config files, however that depends on updates to Configurate happening first. Regardless of that, every config option in the plugin having round-tripped descriptive comments is already further explanation than most plugins give, and so that is a very low priority issue for me.

Out of the other things you've requested here (which each feature request is meant for one request...) the only one I can see myself implementing is the sound options, i.e. Sound Source/Channel (master, ambient, etc.), and sound volumes/pitch. I am going to close this issue as it's quite unfocused, and open a [new issue](https://github.com/jmanpenilla/AnnouncerPlus/issues/40) for those sound options.

The "Sound Animations" you want is out of scope for this plugin, and would be best accomplished by having AnnouncerPlus run another plugins command which has this feature.

As far as an immediate solution to play customized sounds, I would recommend you to use AnnouncerPlus' ability to run commands to use ``/playsound`` to play your customized sounds to players. As described in the config comments, these commands support PlaceholderAPI, so you could use a command like so: ``playsound block.note_block.xylophone master %player_name%`` in the ``join-commands`` section of your join-quit config.
